### ISSUE TITLE
[Dribbblish] Playlist icons don't load

### ISSUE THREAD

**Issue by leon-sm** [spicetify/spicetify-themes#567] opened 2021-10-11 12:17 UTC
Playlist/playlist folder icons often don't show up. Using custom playlist icons does not fix the issue, restarting spotify usually does.

![Screenshot 2021-10-11 135742](https://user-images.githubusercontent.com/68074724/136786792-51005eb2-88c9-41c9-bb03-1bcab4aa1c5a.png)

**Logs**
vendor~xpui.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2487610)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2489892)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2136447
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2729463)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2753315)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2926970)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2698971)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2753094)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2737865)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2736787)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2699243
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2926970)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2698971)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2699188)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2699123)
    at Ss (https://xpui.app.spotify.com/vendor~xpui.js:29:2737286)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2763699)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2766810)
    at https://xpui.app.spotify.com/xpui.js:1:1031261
(anonymous) @ vendor~xpui.js:1
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/644.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

 - OS: Windows 10
 - Spotify version 1.1.69
 - Spicetify version 2.7.0
 - Theme name: Dribbblish

**Comment by morpheusthewhite** [comment] 2021-10-11 14:38
You probably didn't install Dribbblish correctly. Please follow the guide

**Comment by leonscm** [comment] 2021-10-16 12:34
> You probably didn't install Dribbblish correctly. Please follow the guide

Reinstalled it through the install.ps1 file and icons still don't load. Seems to only be the case when spotify starts with windows.

**Comment by Sxxov** [comment] 2021-11-03 00:39
The stacktrace provided doesn't give any indication of what's going wrong (just some warnings, error from the telemetry server, devtools not finding the sourcemaps for the minified files) but I can reproduce this issue as well. Issue persisted from Windows 10 to 11, & can be fixed with a reload via ctrl+shift+R after the first load. It sounds like a classic race condition bug but no extra ideas on where it's coming from.

**Comment by khanhas** [comment] 2021-11-14 12:32
Please upgrade everything to the latest, Spotify, spicetify and dribbblish theme.

**Comment by SebiTalent04** [comment] 2021-11-29 23:06
The problem is still there
Spotify 1.1.73.517
Spicetify 2.7.1
Theme installed through the .ps1 thingy
![image](https://user-images.githubusercontent.com/52084701/143956737-4eb878c2-aa85-4b6a-877a-90a65507cc0f.png)

**Comment by afonsojramos** [comment] 2022-03-05 11:53
Tested locally and this is already working.

**Closed by afonsojramos** 2022-03-05 11:53 UTC
Labels: 🐛 bug

**Comment by leon-sm** [comment] 2022-03-16 17:01
> Tested locally and this is already working.

Not for me, I'm using latest Spotify, Spicetify and Dribblish
